export const leonardo_quotes = [
  "All our knowledge has its origins in our perceptions.",
  "A poet knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.",
  "Art is never finished, only abandoned.",
  "Art is the queen of all sciences communicating knowledge to all the generations of the world.",
  "Details make perfection, and perfection is not a detail.",
  "Every now and then go away, have a little relaxation, for when you come back to your work your judgment will be surer. Go some distance away because then the work appears smaller and more of it can be taken in at a glance and a lack of harmony and proportion is more readily seen.",
  "Fix your course to a star and you can navigate through any storm",
  "He who can copy can do.",
  "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.",
  "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
  "It is an acknowledged fact that we perceive errors in the work of others more readily than in our own.",
  "It's easier to resist at the beginning than at the end.",
  "Learning is the only thing the mind never exhausts, never fears, and never regrets.",
  "Life is pretty simple: You do some stuff. Most fails. Some works. You do more of what works. If it works big, others quickly copy it. Then you do something else. The trick is the doing something else.",
  "Make your work to be in keeping with your purpose",
  "Nothing can be loved or hated unless it is first understood.",
  "Once you have tasted flight, you will forever walk the earth with your eyes turned skyward, for there you have been, and there you will always long to return.",
  "One can have no smaller or greater mastery than mastery of oneself.",
  "Principles for the Development of a Complete Mind: Study the science of art. Study the art of science. Develop your senses- especially learn how to see. Realize that everything connects to everything else.",
  "Realize that everything connects to everything else.",
  "Simplicity is the ultimate sophistication.",
  "Study without desire spoils the memory, and it retains nothing that it takes in.",
  "The acquisition of knowledge is always of use to the intellect, because it may thus drive out useless things and retain the good. For nothing can be loved or hated unless it is first known.",
  "The artist sees what others only catch a glimpse of.",
  "The greatest deception men suffer is from their own opinions.",
  "The noblest pleasure is the joy of understanding.",
  "The painter has the Universe in his mind and hands.",
  "There are three classes of people: those who see. Those who see when they are shown. Those who do not see.",
  "The supreme misfortune is when theory outstrips performance",
  "The worst evil which can befall the artist is that his work should appear good in his own eyes.",
  "To become an artist you have to be curious.",
  "Why does the eye see more clearly when asleep than the imagination when awake?",
]
